
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package source_compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRNT = 11;
  public static final int TTLY = 40;
  public static final int TTLX = 39;
  public static final int TYPED = 7;
  public static final int TTL = 38;
  public static final int TYPEC = 8;
  public static final int STRNG = 3;
  public static final int SMINUS = 49;
  public static final int HSTGRM = 36;
  public static final int WDIV = 25;
  public static final int GLINE = 35;
  public static final int WMUL = 24;
  public static final int SAT = 13;
  public static final int WMOD = 26;
  public static final int CMM = 14;
  public static final int ASIGCLMN = 19;
  public static final int GPIE = 34;
  public static final int VLS = 44;
  public static final int GBAR = 33;
  public static final int VRBL = 6;
  public static final int DPOINTS = 15;
  public static final int EOF = 0;
  public static final int LSBRCKT = 45;
  public static final int ASIG = 16;
  public static final int SMCLN = 17;
  public static final int RSBRCKT = 46;
  public static final int error = 1;
  public static final int SEQLS = 18;
  public static final int WSUM = 22;
  public static final int WMED = 27;
  public static final int CNSL = 10;
  public static final int WVRNZ = 30;
  public static final int RArrow = 50;
  public static final int ENDPRGRM = 21;
  public static final int LSPRTH = 47;
  public static final int NMBR = 2;
  public static final int CLMN = 12;
  public static final int RSPRTH = 48;
  public static final int WMEDN = 28;
  public static final int WRES = 23;
  public static final int END = 9;
  public static final int ARR = 5;
  public static final int LBL = 43;
  public static final int AXISY = 42;
  public static final int AXISX = 41;
  public static final int WMX = 31;
  public static final int LARROW = 51;
  public static final int EXEC = 37;
  public static final int WMDA = 29;
  public static final int NAMEVAR = 4;
  public static final int WMN = 32;
  public static final int PRGRM = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NMBR",
  "STRNG",
  "NAMEVAR",
  "ARR",
  "VRBL",
  "TYPED",
  "TYPEC",
  "END",
  "CNSL",
  "PRNT",
  "CLMN",
  "SAT",
  "CMM",
  "DPOINTS",
  "ASIG",
  "SMCLN",
  "SEQLS",
  "ASIGCLMN",
  "PRGRM",
  "ENDPRGRM",
  "WSUM",
  "WRES",
  "WMUL",
  "WDIV",
  "WMOD",
  "WMED",
  "WMEDN",
  "WMDA",
  "WVRNZ",
  "WMX",
  "WMN",
  "GBAR",
  "GPIE",
  "GLINE",
  "HSTGRM",
  "EXEC",
  "TTL",
  "TTLX",
  "TTLY",
  "AXISX",
  "AXISY",
  "LBL",
  "VLS",
  "LSBRCKT",
  "RSBRCKT",
  "LSPRTH",
  "RSPRTH",
  "SMINUS",
  "RArrow",
  "LARROW"
  };
}

